GET http://localhost:8000

////////Login Route////////
POST http://localhost:8000/auth/login

///////Register Route//////
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "email" : "stephsorandom@gmail.com",
    "password" : "1234"
}

///////Refresh Token Route//
POST http://localhost:8000/auth/refresh-token

//////Logout Route/////////
DELETE http://localhost:8000/auth/logout